name: Build & Push to GHCR

on:
  push:
    branches:
      - dev
    tags:
      - 'v*'

jobs:
  build-and-push-ui:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker tags
        id: docker_tags
        run: |
          # Get build number
          BUILD_NUM=${{ github.run_number }}

          # Adjust names
          ORG_NAME=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          REPO_NAME=$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')

          # Default values - for dev branch
          UI_TAGS="ghcr.io/${ORG_NAME}/${REPO_NAME}:dev-build.${BUILD_NUM} ghcr.io/${ORG_NAME}/${REPO_NAME}:dev"

          # If this is a tag push (for master)
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
            UI_TAGS="ghcr.io/${ORG_NAME}/${REPO_NAME}:${VERSION} ghcr.io/${ORG_NAME}/${REPO_NAME}:latest"
          fi

          echo "ui_tags=${UI_TAGS}" >> $GITHUB_OUTPUT

      - name: Login to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Build UI Image
        run: |
          docker build --no-cache -t temp-ui-image .

      - name: Tag and Push UI Image
        run: |
          for TAG in ${{ steps.docker_tags.outputs.ui_tags }}; do
            docker tag temp-ui-image $TAG
            docker push $TAG
          done
